parameters:
    copyright: 'Radosław Jaros'
    domain: cms.radoslawjaros.pl
    version: '1.0'
    language: pl
    siteName: 'CMS Radosław Jaros'
    siteDescription: 'CMS zaprojektowany dla małych firm'
    siteKeyWords: 'CMS, Radosław Jaros, zarządzanie treścią, strona firmowa'
    contactEmail: jaros_radek@op.pl
    rsaPub: 'rsaPub - test'
    rsaPrivate: 'rsaPrivate - test'
    flEnable: true
