rj_admin_homepage:
    pattern:  /
    defaults: { _controller: RJAdminBundle:Default:index }

rj_admin_settings_general:
    pattern: /settings/general
    defaults: { _controller: RJAdminBundle:Settings:index }

rj_admin_settings_category:
    pattern: /settings/category
    defaults: { _controller: RJAdminBundle:Category:index }

rj_admin_settings_category_add:
    pattern: /settings/category/add
    defaults: { _controller: RJAdminBundle:Category:add }

rj_admin_settings_category_edit:
    pattern: /settings/category/edit/{id}
    defaults: { _controller: RJAdminBundle:Category:edit }

rj_admin_settings_category_remove:
    pattern: /settings/category/remove/{id}
    defaults: { _controller: RJAdminBundle:Category:remove }