imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @RJAdminBundle/Resources/config/parameters.yml }

framework:
    #esi:             ~
    translator:      { fallback: %language% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%language%"
    trusted_proxies: ~
    session:
        handler_id: ~
        cookie_domain: %domain%
        save_path: %kernel.root_dir%/var/sessions
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        cms:
            title: "%siteName%"
            description: "%siteDescription%"
            keywords: "%siteKeyWords%"
            siteEnable: "%flEnable%"
            contactEmail: "%contactEmail%"
            version: "%version%"
            language: "%language%"
            copyright: "Rados≈Çaw Jaros"

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    #bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        lessphp:
            apply_to: "\.less$"
            file:   %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        mapping_types:
            enum: string
            varbinary: string
            tinyblob: text

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        #auto_mapping: true
        entity_managers:
            default:
                auto_mapping: true
                # New custom filter
                filters:
                    oneLocale:
                        class: A2lix\I18nDoctrineBundle\Doctrine\ORM\Filter\OneLocaleFilter
                        enabled: true

stof_doctrine_extensions:
    default_locale: %language%
    orm:
        default:
            sluggable: true
            loggable: false
            timestampable: false
            tree: false
            translatable: false
            sortable: true

a2lix_translation_form:
    locales: [pl, en]       # [optional] Array of the translation locales (The default locale have to be excluded). Can also be specified in the form builder.
    default_required: true     # [optional] Defaults to false. In this case, translation fields are not mark as required with HTML5.
    manager_registry: doctrine
    templating: "RJAdminBundle:Category:translations/form.html.twig" # The default template is Twitter Bootstrap compatible. You can redefine your own template

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: RJ\UserBundle\Entity\User
    service:
        mailer: fos_user.mailer.twig_swift
    registration:
        form:
            type: rj_user_registration

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    port:      %mailer_port%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }
