rj_admin:
    resource: "@RJAdminBundle/Resources/config/routing.yml"
    prefix:   /

rj_user:
    resource: "@RJUserBundle/Resources/config/routing.yml"
    prefix:   /

rj_public:
    resource: "@RJPublicBundle/Resources/config/routing.yml"
    prefix:   /

